apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: bubu
  name: bubu
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bubu
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bubu
    spec:
      containers:
      - image: httpd
        name: httpd
        resources: {}
status: {}
